spring:
  application:
    name: "configserver"
  profiles:
#    active: "native"
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "file:D://learn-microservice-eazybyte//section6//v2-springboot//configserver//src//main//resources//config"
#          search-locations: "classpath:/config/"
        git:
          uri: "https://github.com/nguyenquangos0302git/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "C4F557EB73B3A12163EDD3CDF3458"

server:
  port: 8071

logging:
  level:
    com:
      eazybytes:
        configserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}] - %m%n"