services:
  accounts:
    image: "nguyenquangos0302app/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nguyenquangos0302app
  cards:
    image: "nguyenquangos0302app/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nguyenquangos0302app
  loans:
    image: "nguyenquangos0302app/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nguyenquangos0302app
networks:
  nguyenquangos0302app:
    driver: "bridge"